### PR TITLE
Cleanup .gitignore and ignore built directory

### LINKED ISSUE #42: Gitignore built directory
The source code for this application is written in TypeScript, residing in `/issuebot/src/`.

The `npm start` calls the TypeScript compiler, and puts the resulting JavaScript files in `built` every time you run the application.

I believe it's redundant to have the built directory committed in version control, seeing it gets auto-generated each time you run the app. So I suggest it's a useful candidate to be added to `.gitignore`.

### PR DESCRIPTION
**Pull request by WaveHack**
This fixes #42

### CODE REVIEW

**Review by MythicManiac — APPROVED** [review]
Nice change 👍

**Comment by MythicManiac** [comment]
Looks like this has to be rebased before merging

**Comment by WaveHack** [comment]
Just did a rebase, but it also marks the files changed which were merged by you earlier.

I suspect this won't cause an issue. If you want me to open a new PR just in case, let me know.

**Comment by MythicManiac** [comment]
It looks like the rebase wasn't done properly (due to the old commits also showing on this PR). Easiest way to fix this would probably be to re-do the changes in a clean branch and PR with that.

Optionally I can squash merge, if that's too much work.

**Comment by WaveHack** [comment]
I'll make a new clean PR!

**Pull request closed without merging**
